CREATE TABLE STUDENT_TORONTO(
 STU_ID INT IDENTITY(100000,1),
 STU_ID_UNIV AS 'UOT-' + CAST(STU_ID AS VARCHAR(20)) PERSISTED NOT NULL,
 STU_NAME VARCHAR(40),
 STU_DOB DATE,
 STU_DOJ DATE,
 STU_DOG DATE,
 STU_ADDRESS VARCHAR(50),
 STU_CITY VARCHAR(50),
 STU_PROVINCE VARCHAR(5),
 STU_ZIP_CODE VARCHAR(6),
 STU_EMAIL VARCHAR(50),
 STU_MOB NUMERIC(10),
 STU_PAR_FNAME VARCHAR(20),
 STU_PAR_LNAME VARCHAR(20),
 STU_PAR_MOB NUMERIC(10),
 PRIMARY KEY(STU_ID)
)
SELECT * FROM STUDENT_TORONTO

 UPDATE  STUDENT_TORONTO 
 SET STU_CITY='tot' WHERE STU_ID=100000

DROP TABLE STUDENT_TORONTO
INSERT INTO STUDENT_TORONTO (STU_NAME, STU_DOB, STU_DOJ, STU_DOG, STU_ADDRESS, STU_CITY, STU_PROVINCE
, STU_ZIP_CODE, STU_EMAIL, STU_MOB, STU_PAR_FNAME, STU_PAR_LNAME, STU_PAR_MOB) VALUES ('RON WEASLY', 
'1995-06-18', '2015-09-02', NULL, '2934', 'TORONTO', 'ON', 'N101L9', 'ron@utoronto.ca', 5191236845, 'JACK',
 'WEASLY', 9805636567)
 INSERT INTO STUDENT_TORONTO (STU_NAME, STU_DOB, STU_DOJ, STU_DOG, STU_ADDRESS, STU_CITY, STU_PROVINCE
, STU_ZIP_CODE, STU_EMAIL, STU_MOB, STU_PAR_FNAME, STU_PAR_LNAME, STU_PAR_MOB) VALUES ('ZARNA PRAJAPATI', 
'1994-02-28', '2016-02-02', '2018-01-01', '2912', 'Toronto', 'ON', 'J9C1J9', 'zarna@utoronto.ca', 5158768765, 'PRIYA',
 'PRAJAPATI', 6788766780)
 INSERT INTO STUDENT_TORONTO (STU_NAME, STU_DOB, STU_DOJ, STU_DOG, STU_ADDRESS, STU_CITY, STU_PROVINCE
, STU_ZIP_CODE, STU_EMAIL, STU_MOB, STU_PAR_FNAME, STU_PAR_LNAME, STU_PAR_MOB) VALUES ('CHUKA MULUKUTLA', 
'1989-08-18', '2015-09-01', NULL, '2767', 'Toronto', 'ON', 'N8C1K9', 'chuka@utoronto.ca', 5098789123, 'CHUKLA',
 'MULUKUTLA', 2765456123)

 INSERT INTO STUDENT_HUMBER (STU_FNAME, STU_LNAME, STU_DOB, STU_DOJ, STU_DOG, STU_ADDRESS, STU_CITY, STU_PROVINCE
, STU_ZIP_CODE, STU_EMAIL, STU_MOB, STU_PAR_FNAME, STU_PAR_LNAME, STU_PAR_MOB) VALUES ('PRUDVI', 'MALLU', 
'1987-02-03', '2017-09-08', NULL, '678', 'Humber', 'ON', 'N9X6J7', 'PRUDVI@uhumber.ca', 6734510045, 'PREM',
 'JUOSH', 7654389082)
 INSERT INTO STUDENT_HUMBER (STU_FNAME, STU_LNAME, STU_DOB, STU_DOJ, STU_DOG, STU_ADDRESS, STU_CITY, STU_PROVINCE
, STU_ZIP_CODE, STU_EMAIL, STU_MOB, STU_PAR_FNAME, STU_PAR_LNAME, STU_PAR_MOB) VALUES ('TASHI', 'TSERING', 
'1990-06-20', '2016-09-02', '2018-02-23', '2907', 'Humber', 'ON', 'N9D1L9', 'tashi@uhumber.ca', 2199736845, 'KUNCHOK',
 'DORJEE', 9805636707)
SELECT * FROM STUDENT_HUMBER

CREATE TABLE COURSE_TORONTO(
 COURSE_ID INT,
 COURSE_NAME VARCHAR(20),
 COURSE_DESC VARCHAR(100),
 --STU_ID INT,
-- STU_ID_UNIV VARCHAR(20),
 COURSE_CREDIT NUMERIC CHECK(COURSE_CREDIT IN(0,3)),
 PRIMARY KEY(COURSE_ID)
 --CONSTRAINT STU_ID1_FK FOREIGN KEY (STU_ID) REFERENCES STUDENT_HUMBER(STU_ID)
 --CONSTRAINT STU_ID_UNIV_FK FOREIGN KEY (STU_ID_UNIV) REFERENCES STUDENT_HUMBER(STU_ID_UNIV)
)
 
INSERT INTO COURSE_TORONTO VALUES(100, 'SOFTWARE ENGINEERING','THIS COURSE IS ABOUT SOFTWARE ENGINEERING', 3)
INSERT INTO COURSE_TORONTO VALUES(200, 'NETWORK', 'THIS COURSE IS ABOUT NETWORKING',3)
INSERT INTO COURSE_TORONTO VALUES(300, 'C++','THIS COURSE IS ABOUT C++', 3)
INSERT INTO COURSE_TORONTO VALUES(400, 'PY','THIS COURSE IS ABOUT PYTHON', 3)
INSERT INTO COURSE_TORONTO VALUES(500, 'UNIX', 'THIS COURSE IS ABOUT UNIX PROGRAMMING', 3)
INSERT INTO COURSE_TORONTO VALUES(600, 'SOCKETS', 'THIS COURSE IS ABOUT SOCKET PROGRAMMING', 3)
DROP TABLE COURSE_HUMBER

SELECT * FROM COURSE_TORONTO
CREATE TABLE MARKS_TORONTO(
 MARK_ID INT IDENTITY(1,1),
 --COURSE_ID INT,
 ENROLL_ID INT,
-- STU_ID INT,
 MARKS_OBTAINED NUMERIC(5,2),
 PRIMARY KEY(MARK_ID),
  CONSTRAINT ENROLL_ID_FK FOREIGN KEY (ENROLL_ID) REFERENCES ENROLL_TORONTO(ENROLL_ID),
 -- CONSTRAINT STU_ID3_FK FOREIGN KEY (STU_ID) REFERENCES COURSE_HUMBER(STU_ID),

)
SELECT * FROM STUDENT_HUMBER
SELECT * FROM ENROLL_HUMBER
SELECT * FROM COURSE_HUMBER
SELECT * FROM MARKS_HUMBER
DROP TABLE MARKS_HUMBER
SELECT * FROM ENROLL_TORONTO
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (9,74.32)
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (10,89.00)
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (11,90.98)
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (12,83.44)
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (13,91.67)
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (14,48)
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (15,62.44)
INSERT INTO MARKS_TORONTO (ENROLL_ID,MARKS_OBTAINED)VALUES (16,31.89)
INSERT INTO MARKS_HUMBER (ENROLL_ID,MARKS_OBTAINED)VALUES (9,68.09)
INSERT INTO MARKS_HUMBER (ENROLL_ID,MARKS_OBTAINED)VALUES (10,44.67)
INSERT INTO MARKS_HUMBER (ENROLL_ID,MARKS_OBTAINED)VALUES (11,56.00)
INSERT INTO MARKS_HUMBER (ENROLL_ID,MARKS_OBTAINED)VALUES (12,98.98)
INSERT INTO MARKS_HUMBER (ENROLL_ID,MARKS_OBTAINED)VALUES (13,100.00)
INSERT INTO MARKS_HUMBER (ENROLL_ID,MARKS_OBTAINED)VALUES (14,87.21)
 CREATE TABLE ENROLL_TORONTO(
 ENROLL_ID INT IDENTITY(1,1),
 STU_ID INT,
 COURSE_ID INT,
 PRIMARY KEY(ENROLL_ID),
 CONSTRAINT STU_ID_FK FOREIGN KEY (STU_ID) REFERENCES STUDENT_TORONTO(STU_ID),
 CONSTRAINT COURSE_ID1_FK FOREIGN KEY (COURSE_ID) REFERENCES COURSE_TORONTO(COURSE_ID)
)
SELECT * FROM STUDENT_TORONTO
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100000,100)
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100000,300)
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100000,400)
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100001,100)
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100001,200)
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100001,500)
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100002,400)
INSERT INTO ENROLL_TORONTO (STU_ID,COURSE_ID) VALUES (100002,500)
INSERT INTO ENROLL_HUMBER (STU_ID,COURSE_ID) VALUES (4,1)
INSERT INTO ENROLL_HUMBER (STU_ID,COURSE_ID) VALUES (4,3)
INSERT INTO ENROLL_HUMBER (STU_ID,COURSE_ID) VALUES (4,2)
INSERT INTO ENROLL_HUMBER (STU_ID,COURSE_ID) VALUES (5,3)
INSERT INTO ENROLL_HUMBER (STU_ID,COURSE_ID) VALUES (5,1)
INSERT INTO ENROLL_HUMBER (STU_ID,COURSE_ID) VALUES (5,5)

SELECT * FROM ENROLL_HUMBER
DROP TABLE FEE_HUMBER
DROP TABLE MARKS_HUMBER
DROP TABLE COURSE_HUMBER
DROP TABLE ENROLL_HUMBER

CREATE TABLE FEE_TORONTO(
 FEE_ID INT IDENTITY(1,1),
 STU_ID INT,
 FEE_AMOUNT NUMERIC(10),
 FEE_DESC VARCHAR(20),
 FEE_DATE DATE,
 PRIMARY KEY(FEE_ID),
  CONSTRAINT STU_ID2_FK FOREIGN KEY (STU_ID) REFERENCES STUDENT_TORONTO(STU_ID)
)
SELECT * FROM STUDENT_TORONTO

INSERT INTO FEE_TORONTO (STU_ID,FEE_AMOUNT,FEE_DESC,FEE_DATE)
VALUES(100000,1500,'TUTION FEE','2015-09-02')

INSERT INTO FEE_TORONTO  (STU_ID,FEE_AMOUNT,FEE_DESC,FEE_DATE)
VALUES(100001,1500,'TUTION FEE','2016-02-02')
INSERT INTO FEE_TORONTO  (STU_ID,FEE_AMOUNT,FEE_DESC,FEE_DATE)
VALUES(100002,1500,'TUTION FEE','2015-09-01')
INSERT INTO FEE_TORONTO  (STU_ID,FEE_AMOUNT,FEE_DESC,FEE_DATE)
VALUES(100001,500,'GRADUATION FEE','2018-01-01')
INSERT INTO FEE_HUMBER  (STU_ID,FEE_AMOUNT,FEE_DESC,FEE_DATE)
VALUES(5,1000,'TUTION FEE','2016-09-02')

INSERT INTO FEE_HUMBER  (STU_ID,FEE_AMOUNT,FEE_DESC,FEE_DATE)
VALUES(5,500,'GRAD FEE','2018-02-23')
INSERT INTO FEE_HUMBER  (STU_ID,FEE_AMOUNT,FEE_DESC,FEE_DATE)
VALUES(2,500,'GRAD FEE','2018-01-01')

SELECT * FROM STUDENT_HUMBER
SELECT * FROM ENROLL_HUMBER
SELECT * FROM COURSE_HUMBER
SELECT * FROM MARKS_HUMBER
SELECT * FROM FEE_HUMBER
